export const TASK_SYMBOLS = {
    TASK_REPOSITORY: Symbol('TASK_REPOSITORY'),
    TASK_LIST: Symbol('TASK_LIST'),
    TASK_CREATE: Symbol('TASK_CREATE'),
    TASK_DELETE: Symbol('TASK_DELETE'),
    TASK_SEARCH: Symbol('TASK_SEARCH'),
    TASK_COMPLETE: Symbol('TASK_COMPLETE')

}